version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      application-dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      workflow-actions:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /poc/apps/spiffe
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    groups:
      spiffe-dependencies:
        patterns:
          - "*"
