server {
    bind_address = "0.0.0.0"
    bind_port = "8081"
    trust_domain = "lab.local"
    data_dir = "/run/spire/data"
    log_level = "INFO"
    ca_ttl = "168h"
    default_x509_svid_ttl = "1h"
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "sqlite3"
            connection_string = "/run/spire/data/datastore.sqlite3"
        }
    }

    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            keys_path = "/run/spire/data/keys.json"
        }
    }
}
